### ISSUE TITLE
Consider removing Clang.jl as a direct dependency?

### ISSUE THREAD

**Issue by Gnimuc** [fieldofnodes/QuEST.jl#13]
https://github.com/fieldofnodes/QuEST.jl/blob/main/src/gen/wrapper.jl

Clang.jl is only used at the "compile" time when you run the script above.  There is no need to install Clang.jl on the user side.

**Comment by fieldofnodes** [comment]
Hi, very sorry for thepoorly timed reply. Yes that is a good idea. I had originally wanted he give the user an option to re-compile, but now I think you are right.

**Comment by fieldofnodes** [comment]
I have removed this and separated the compile - function regen code.
