### ISSUE TITLE
Error handling in Julia notebooks

### ISSUE THREAD

**Issue by joeybarreto** [fieldofnodes/QuEST.jl#15]
I'm trying to run QuEST.jl in a .ipynb notebook with a Julia 1.10.3 kernel in VSCode, and the code snippet below works as expected:
```
using QuEST
num_qubits = 2
env = createQuESTEnv()
  
# create a 2 qubit register in the zero state
qubits = createQureg(num_qubits, env)
initZeroState(qubits)

# apply circuit
hadamard(qubits, 1) #<-- line to change
controlledNot(qubits, 1, 2)
measure(qubits, 2)

# unload QuEST
destroyQureg(qubits, env)
destroyQuESTEnv(env)
```

but if I change the indicated line ```hadamard(qubits, 1)``` to ```hadamard(qubits, 3)``` (in order to cause an error), the cell just hangs and runs (forever?).  Is there some error from QuEST that's not being passed to QuEST.jl properly?  Or perhaps this is an issue just within the notebook environment?

**Comment by joeybarreto** [comment]
Running the script directly in Julia throws the expected error, so indeed it is related to the error passing into VS Code.

**Comment by fieldofnodes** [comment]
Thank you for the issue. I will look into this as well. So if I understand correctly, the Jupyter notebook as running in VSCode will not throw the error, but will hang. And when you run it in Julia directly it throws the correct error.

A solution in mind that relates to the issue of index in general is to have a Julia based exception that is thrown whenever the index is out of bounds and so does not rely on QuEST in C directly. 

I will open an Issue to get this sorted.

I will need to test it, but if I have a Julia error I think it would through the error in Jupyter directly.

But it may be the case that Jupyter is not reactive to this type of error.

**Comment by fieldofnodes** [comment]
@joeybarreto I added error handling to throw Julia based errors on most, functions that call qubit indices in some form.

Let me know if you have any other issues.

Note, I am still testing.
