### ISSUE TITLE
Indexing issue with multiRotatePauli

### ISSUE THREAD

**Issue by joeybarreto** [fieldofnodes/QuEST.jl#16]
Running 
```
num_qubits = 4
env = createQuESTEnv()
  
# create a 2 qubit register in the zero state
qubits = createQureg(num_qubits, env)
initZeroState(qubits)

multiRotatePauli(qubits, [1,2,3], [1,2,3], 3, .1).   #<-- line to change

# unload QuEST
destroyQureg(qubits, env)
destroyQuESTEnv(env)
```

fails with error `QuEST Error in function multiRotatePauli: The target qubits must be unique.`. Changing the indicated line to `multiRotatePauli(qubits, [4,2,3], [1,2,3], 3, .1)` succeeds, so there's an issue with the fact that qubit 1 specifically is being acted upon, which makes me suspect there's an issue between the 0/1 indexing conversion.

**Comment by fieldofnodes** [comment]
Here is the link to the C QuEST API:

[https://quest-kit.github.io/QuEST/group__unitary.html#ga34aa4865c92f9aa5d898c91286c9eca5](https://quest-kit.github.io/QuEST/group__unitary.html#ga34aa4865c92f9aa5d898c91286c9eca5)


And here are the lines to this function:

```julia
function multiRotatePauli(qureg, targetQubits, targetPaulis, numTargets, angle)
    targetQubits = [c_shift_index(q) for q in targetQubits]
    @ccall libquest.multiRotatePauli(qureg::Qureg, targetQubits::Ptr{Cint}, targetPaulis::Ptr{pauliOpType}, numTargets::Cint, angle::Cdouble)::Cvoid
end
```

I agree with what you are saying. The `targetPaulis::Ptr{pauliOpType}`, which is an Enum I think is the issue.

I will look this over as soon as I can.

Thank you again for raising the issue.

**Comment by joeybarreto** [comment]
yes it appears that the `enum` here is the issue, in the QuEST [example](https://quest-kit.github.io/QuEST/group__unitary.html#ga34aa4865c92f9aa5d898c91286c9eca5), it reads
`
multiRotatePauli(qureg, (int[]) {4,5,8,9}, (int[]) {0,1,2,3}, 4, .1)
`
which is incorrect, which confused me as well

**Comment by fieldofnodes** [comment]
So I have created C/C++ QuEST version



```c++
#include <QuEST.h>
#include <iostream>
#include <vector>



int main() {


    // set num qubits
    int num_qubits = 4;
    std::vector<int> targets = {0,1,2,3};
   
    
    int num_targets = 4;

    std::vector<pauliOpType> paulis_enum = {PAULI_I, PAULI_X, PAULI_Y, PAULI_Z};
    std::vector<int> int_paulis = {0, 1, 2, 3};
    std::vector<pauliOpType> paulis;

    for (const auto& int_pauli : int_paulis) {
        paulis.push_back(static_cast<pauliOpType>(int_pauli));
    }

    for (const auto& pauli : paulis) {
        std::cout << pauli << '\n';
    }

    for (const auto& pauli : paulis_enum) {
        std::cout << pauli << '\n';
    }


    qreal angle = 0.1;

    // load QuEST
    QuESTEnv env = createQuESTEnv();

    // create a 2 qubit register in the zero state
    Qureg qureg = createQureg(num_qubits, env);
    initZeroState(qureg);

    multiRotatePauli(qureg, targets.data(), paulis.data(), num_targets, angle);


    // unload QuEST
    destroyQureg(qureg, env);
    destroyQuESTEnv(env);
    

    return 0;
}
```

Then the output values for each version of the `enum`


```c++
0
1
2
3
0
1
2
3
```

First 4 and second 4 are just repeats. So these are also the same as the targets. The function runs as well. So I believe QuEST in C/C++ runs as expected. Now I will look at `QuEST.jl` and see what I need to do.

Thanks again.

**Comment by fieldofnodes** [comment]
I have updated the function itself that does `ccall`

```julia
function multiRotatePauli(qureg::Qureg, targetQubits::Vector{Int}, targetPaulis::Union{Vector{pauliOpType},Vector{Int}}, angle)
    test_qubit_present(qureg, targetQubits)
    targetQubits = [c_shift_index(q) for q in targetQubits] |> pointer
    targetPaulis = [convert_to_cPauliOpType(tps) for tps in targetPaulis] |> pointer
    numTargets = length(targetQubits)
    @ccall libquest.multiRotatePauli(qureg::Qureg, targetQubits::Ptr{Cint}, targetPaulis::Ptr{cPauliOpType}, numTargets::Cint, angle::Cdouble)::Cvoid
end
```

Note that I was not converting to a pointer for the target qubits nor for the Pauli OP types

Now you can pass the enum or the integer



```julia
num_qubits = 5
env = createQuESTEnv()
  
# create a 2 qubit register in the zero state
qureg = createQureg(num_qubits, env)
initZeroState(qureg)

multiRotatePauli(qureg, [1,2,3,4], [PAULI_I,PAULI_X,PAULI_Y,PAULI_Z], .1)  #<-- Use enum directly6
multiRotatePauli(qureg, [1,2,3,4], [1,1,2,3], .1)  #<-- Or use integer values

# unload QuEST
destroyQureg(qureg, env)
destroyQuESTEnv(env)
```

**Comment by fieldofnodes** [comment]
Do you mind cloning this branch and testing that this now works as you expected? @joeybarreto Thank you.

**Comment by fieldofnodes** [comment]
Closing.
